# Generated by Django 4.0.4 on 2022-05-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_beer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='voltage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
